#loc = loc("/workspace/triton-ascend/docs/zh/examples/vecadd.py":9:0)
#loc9 = loc("x_ptr"(#loc))
#loc10 = loc("y_ptr"(#loc))
#loc11 = loc("output_ptr"(#loc))
#loc12 = loc("n_elements"(#loc))
module attributes {hacc.target = #hacc.target<"Ascend910B4-1">} {
  func.func @add_kernel(%arg0: memref<?xi8> loc("/workspace/triton-ascend/docs/zh/examples/vecadd.py":9:0), %arg1: memref<?xi8> loc("/workspace/triton-ascend/docs/zh/examples/vecadd.py":9:0), %arg2: memref<?xf32> {tt.divisibility = 16 : i32, tt.tensor_kind = 0 : i32} loc("x_ptr"(#loc)), %arg3: memref<?xf32> {tt.divisibility = 16 : i32, tt.tensor_kind = 0 : i32} loc("y_ptr"(#loc)), %arg4: memref<?xf32> {tt.divisibility = 16 : i32, tt.tensor_kind = 1 : i32} loc("output_ptr"(#loc)), %arg5: i32 {tt.divisibility = 16 : i32} loc("n_elements"(#loc)), %arg6: i32 loc("/workspace/triton-ascend/docs/zh/examples/vecadd.py":9:0), %arg7: i32 loc("/workspace/triton-ascend/docs/zh/examples/vecadd.py":9:0), %arg8: i32 loc("/workspace/triton-ascend/docs/zh/examples/vecadd.py":9:0), %arg9: i32 loc("/workspace/triton-ascend/docs/zh/examples/vecadd.py":9:0), %arg10: i32 loc("/workspace/triton-ascend/docs/zh/examples/vecadd.py":9:0), %arg11: i32 loc("/workspace/triton-ascend/docs/zh/examples/vecadd.py":9:0)) attributes {SyncBlockLockArgIdx = 0 : i64, WorkspaceArgIdx = 1 : i64, global_kernel = "local", mix_mode = "aiv", parallel_mode = "simd"} {
    %cst = arith.constant 0.000000e+00 : f32 loc(#loc13)
    %c1024 = arith.constant 1024 : index loc(#loc14)
    %c1024_i32 = arith.constant 1024 : i32 loc(#loc15)
    %0 = arith.muli %arg9, %c1024_i32 : i32 loc(#loc15)
    %1 = arith.index_cast %0 : i32 to index loc(#loc15)
    %reinterpret_cast = memref.reinterpret_cast %arg2 to offset: [%1], sizes: [1024], strides: [1] : memref<?xf32> to memref<1024xf32, strided<[1], offset: ?>> loc(#loc16)
    %alloc = memref.alloc() : memref<1024xf32> loc(#loc14)
    %2 = arith.addi %1, %c1024 : index loc(#loc14)
    %3 = arith.index_cast %arg5 : i32 to index loc(#loc12)
    %4 = arith.maxsi %1, %3 : index loc(#loc14)
    %5 = arith.minsi %2, %4 : index loc(#loc14)
    %6 = arith.subi %5, %1 : index loc(#loc14)
    %7 = arith.cmpi slt, %6, %c1024 : index loc(#loc14)
    scf.if %7 {
      linalg.fill ins(%cst : f32) outs(%alloc : memref<1024xf32>) loc(#loc14)
    } {hivm.unlikely_condition} loc(#loc14)
    %subview = memref.subview %reinterpret_cast[0] [%6] [1] : memref<1024xf32, strided<[1], offset: ?>> to memref<?xf32, strided<[1], offset: ?>> loc(#loc14)
    %subview_0 = memref.subview %alloc[0] [%6] [1] : memref<1024xf32> to memref<?xf32, strided<[1]>> loc(#loc14)
    memref.copy %subview, %subview_0 : memref<?xf32, strided<[1], offset: ?>> to memref<?xf32, strided<[1]>> loc(#loc14)
    %8 = bufferization.to_tensor %alloc restrict writable : memref<1024xf32> loc(#loc14)
    %reinterpret_cast_1 = memref.reinterpret_cast %arg3 to offset: [%1], sizes: [1024], strides: [1] : memref<?xf32> to memref<1024xf32, strided<[1], offset: ?>> loc(#loc17)
    %alloc_2 = memref.alloc() : memref<1024xf32> loc(#loc13)
    scf.if %7 {
      linalg.fill ins(%cst : f32) outs(%alloc_2 : memref<1024xf32>) loc(#loc13)
    } {hivm.unlikely_condition} loc(#loc13)
    %subview_3 = memref.subview %reinterpret_cast_1[0] [%6] [1] : memref<1024xf32, strided<[1], offset: ?>> to memref<?xf32, strided<[1], offset: ?>> loc(#loc13)
    %subview_4 = memref.subview %alloc_2[0] [%6] [1] : memref<1024xf32> to memref<?xf32, strided<[1]>> loc(#loc13)
    memref.copy %subview_3, %subview_4 : memref<?xf32, strided<[1], offset: ?>> to memref<?xf32, strided<[1]>> loc(#loc13)
    %9 = bufferization.to_tensor %alloc_2 restrict writable : memref<1024xf32> loc(#loc13)
    %10 = arith.addf %8, %9 : tensor<1024xf32> loc(#loc18)
    %reinterpret_cast_5 = memref.reinterpret_cast %arg4 to offset: [%1], sizes: [1024], strides: [1] : memref<?xf32> to memref<1024xf32, strided<[1], offset: ?>> loc(#loc7)
    %extracted_slice = tensor.extract_slice %10[0] [%6] [1] : tensor<1024xf32> to tensor<?xf32> loc(#loc8)
    %subview_6 = memref.subview %reinterpret_cast_5[0] [%6] [1] : memref<1024xf32, strided<[1], offset: ?>> to memref<?xf32, strided<[1], offset: ?>> loc(#loc8)
    bufferization.materialize_in_destination %extracted_slice in writable %subview_6 : (tensor<?xf32>, memref<?xf32, strided<[1], offset: ?>>) -> () loc(#loc8)
    return loc(#loc)
  } loc(#loc)
} loc(#loc)
#loc1 = loc("/workspace/triton-ascend/docs/zh/examples/vecadd.py":27:16)
#loc2 = loc("/workspace/triton-ascend/docs/zh/examples/vecadd.py":26:16)
#loc3 = loc("/workspace/triton-ascend/docs/zh/examples/vecadd.py":21:24)
#loc4 = loc("/workspace/triton-ascend/docs/zh/examples/vecadd.py":26:24)
#loc5 = loc("/workspace/triton-ascend/docs/zh/examples/vecadd.py":27:24)
#loc6 = loc("/workspace/triton-ascend/docs/zh/examples/vecadd.py":28:17)
#loc7 = loc("/workspace/triton-ascend/docs/zh/examples/vecadd.py":30:26)
#loc8 = loc("/workspace/triton-ascend/docs/zh/examples/vecadd.py":30:35)
#loc13 = loc("y"(#loc1))
#loc14 = loc("x"(#loc2))
#loc15 = loc("block_start"(#loc3))
#loc16 = loc("x"(#loc4))
#loc17 = loc("y"(#loc5))
#loc18 = loc("output"(#loc6))

